### ISSUE TITLE
6.5 Bugs and Crashes

### ISSUE THREAD

**Issue by FromTheGrayve** [Caraxi/SimpleTweaksPlugin#631] opened 2023-10-04 21:57 UTC
From the Dalamund XIV testing discord

Crashes:

Duplicate Action Presses Between Hotbars causes CTD  if bound to a hotkey, but not when using mouseclicks

Extended Desynthesis Window causes CTD if "Add Option to Show All Items" is checked

Improved Crafting Log is breaking on the End Sythesis click to end a craft and switch to another job.

Bugs:

Shield on HP Bar is white instead of the color chosen in tweak

Housing Lottery Timer is not showing the countdown.

**Comment by nebel** [comment] 2023-10-04 23:01
https://github.com/Caraxi/SimpleTweaksPlugin/pull/629 should address the "Shield on HP Bar is white instead of the color chosen in tweak" issue.

**Comment by drejjmit** [comment] 2023-10-05 04:26
'Disable Title Screen Movie' doesn't work

**Comment by Efiyo** [comment] 2023-10-05 05:24
Enabling the class switcher and clicking in the character menu crashes the game, I'll test more with just ST installed to see if maybe there is a conflict with other plugins

**Comment by Caraxi** [comment] 2023-10-05 11:56
> Duplicate Action Presses Between Hotbars causes CTD if bound to a hotkey, but not when using mouseclicks

I've disabled this tweak until it can be fixed. I'm not sure what the issue is right now

> Extended Desynthesis Window causes CTD if "Add Option to Show All Items" is checked

Extended Desynthesis was crashing completely all over the place. I've reworked it in the latest version (56112fe06f4d326e9528dfb5a3274b18c874a11f), but it will be missing the "Show All Items" option until I get time to redo that.

> Improved Crafting Log is breaking on the End Sythesis click to end a craft and switch to another job.

I've hopefully fixed the issue that was causing some people to get deadlocked (e36a3086fbbbe78aa07ee4e906eaccf2fa67783c), some smaller issues will be fixed when dalamud updates ClientStructs 

> Shield on HP Bar is white instead of the color chosen in tweak

Should be fixed as of #629

> Housing Lottery Timer is not showing the countdown.

Should be fixed with b0ce561e9faccded5c8123fa6f53c45841024780

**Comment by folfblues** [comment] 2023-10-05 18:29
Enabling Leave Duty Command throws an error and refuses to activate:

![ffxiv_dx11_c0UchZXA5y](https://github.com/Caraxi/SimpleTweaksPlugin/assets/75710616/30500adb-6e34-411c-8bf3-40ec331676b9)

**Comment by Caraxi** [comment] 2023-10-06 04:39
> Enabling Leave Duty Command throws an error and refuses to activate:
> 
> ![ffxiv_dx11_ss71ieX9Hg](https://user-images.githubusercontent.com/75710616/273005939-83b2bb8f-6114-41a4-9b53-0ff48789988d.png)

You might have another plugin adding the same thing?

**Comment by rockshim** [comment] 2023-10-07 20:59
These settings aren't working as intended
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/134738229/baf4abeb-f7e1-4cab-a073-7376c463ef5b)
Setting them like this should allow you to always see pop-up help and never see cross bar hints but instead both show all the time.
If set like this 
![image](https://github.com/Caraxi/SimpleTweaksPlugin/assets/134738229/1dad0ae1-9d86-4d8a-968b-d0a99636fd65)
then everything is always hidden, when cross bar should appear. This stopped working since 6.4 I think.

**Closed** 2023-10-10 05:05 UTC
