### ISSUE TITLE
Issue where phlegma III cool down changes to small sometimes with large cooldown counter

### ISSUE THREAD

**Issue by nyxalteria** [Caraxi/SimpleTweaksPlugin#157] opened 2021-12-10 11:05 UTC
![image](https://user-images.githubusercontent.com/92659516/145564404-8931dc0c-5776-4cad-a91b-dcf36a206b2b.png)
 I'm not sure whats triggering it, have not noticed this with the earlier versions of phlegma

**Comment by Caraxi** [comment] 2021-12-11 02:28
Duplicate of #156

**Closed by Caraxi** 2021-12-11 02:28 UTC
