### ISSUE TITLE
[Bug] Improved Crafting Log

### ISSUE THREAD

**Issue by tmschorr** [Caraxi/SimpleTweaksPlugin#356] opened 2022-08-05 08:56 UTC
When I use the 'Improved Crafting Log' option on the 'Simple Tweaks' plugin and want to make 'Spiked Steel Labrys', it switches to the Leatherworker instead of the Blacksmith.

**Comment by Caraxi** [comment] 2022-08-05 14:01
I'm unable to reproduce this at all, it switches to the correct job when I try

**Comment by internetfreak** [comment] 2022-08-15 20:09
My girlfriend just recently encountered this issue as well while completing her crafting log. When I tried it, we weren't able to reproduce the issue but now we have found out that the issue occurs when you filter recipes.
With those steps you should be able to reproduce it:

1. Pick any crafting class, e.g. culinarian. To make things a bit easier to reproduce and notice, pick a class where you have some things already crafted.
2. Use the filter recipes option to filter either for uncrafted or recent items. Notice you're still able to craft using your starting class
3. Now select another job and recipe and switch classes, e.g. alchemist. Notice how you switch jobs perfectly fine
4. Return to the job used in step 1. When you now click switch job, you get a somewhat random job instead of the one you need for the craft

**Comment by Frousties** [comment] 2022-08-19 14:11
Can reproduce this issue
When "Hide Completed Recipes" is checked in the advanced settings, it makes you switch to the next class down the list when you try to craft the last item in the window
When unchecked, it behaves as expected

Slightly annoying but not too hard to work around for now

**Comment by Drew-L** [comment] 2022-09-03 18:02
This is happening for me except I don't have any of the settings checked. I was crafting all materials for Fingerless Darkhempen Gloves of Healing, specifically Goldsmith prior to experiencing the bug, and when I finally tried to make the thing, it doesn't work anymore. Might be worth noting that it switches to different jobs for different recipes.

Just disabling and re-enabling seems to have fixed it but I think it's still worth reporting.

**Comment by Drew-L** [comment] 2022-09-03 20:16
Happened to me twice now even after a reboot. It gets triggered by crafting Ametrine, then switching over to Weaver through Fingerless Darkhempen Gloves of Healing.

**Closed** 2023-03-25 07:09 UTC
Labels: Bug
